### PR TITLE
Add solar component

### LINKED ISSUE #20: Add Solar component
Hallo,

kannst du bitte noch die Solarsensoren rein machen?
Adresse 2100-2113 in der Modbus TCP - Registerdaten pdf.

Grüße Sascha

### PR DESCRIPTION
**Pull request by LavermanJJ**
Fixes #20

### CODE REVIEW

**Comment by LavermanJJ** [comment]
@saschaguilliard ,can you confirm that there is an error in the spec for register value 2104 -> Durchfluss. The spec says it's in `Liters` however that is not arate as the time relation is missing. Am I correct to assume it is liters per hour?

**Comment by saschaguilliard** [comment]
I cannot confirm that, but I think its l/min (liter per minute).

Am Mi., 2. Nov. 2022 um 10:57 Uhr schrieb Jeroen Laverman <
***@***.***>:

**Comment by LavermanJJ** [comment]
I tried to double check by finding the manual. There I found the following: 
image
https://www.solarfocus.com/bedienungsanleitungen/pellettop-touch_betriebsanleitung.pdf

@saschaguilliard could you please check if you have a similar screen on your control unit, and if it also shows the `L/h`? Thanks

**Comment by saschaguilliard** [comment]
My view looks like this:
image

And I found this Flowmeter with l/min
https://www.allner-haustechnik.de/solarfocus/speicher/zubehoer-speicher/solarfocus-waermemengenzaehler-elektronisch.htm

**Comment by LavermanJJ** [comment]
@saschaguilliard it would be great if you could check the display again, when the solar module is working. If we are lucky it will display the information similar to the image in the manual.

**Comment by saschaguilliard** [comment]
No,
The flowmeter is an option. I don't have this in my installation...


Jeroen Laverman ***@***.***> schrieb am Do., 3. Nov. 2022,
07:54:

**Comment by LavermanJJ** [comment]
I'll decided to go with `l/h` as it was depicted in their manual. If someone finds out in the future that it does not fit, I'll fix it then.

**Pull request merged**
